name: flutter_supabase_auth
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1

  # Caching
  hydrated_bloc: ^10.0.0
  cached_network_image: ^3.4.1

  # Routing
  go_router: ^15.2.4

  # Localization
  easy_localization: ^3.0.7+1

  # Dependency Injection
  get_it: ^8.0.3

  # Data Class Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  # Utilities
  equatable: ^2.0.7
  logger: ^2.6.0
  path_provider: ^2.1.5
  envied: ^1.1.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.6

  # Functional Programming
  dartz: ^0.10.1

  # DataBases
  supabase_flutter: ^2.9.1

  # Networking
  internet_connection_checker_plus: ^2.7.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  envied_generator: ^1.1.1

  # Linter
  very_good_analysis: ^9.0.0

  # Testing
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  android: true
  ios: true
  color: "#121315"
  image: "assets/images/splash_logo.png"
  android_12:
    image: "assets/images/splash_logo_12.png"
    color: "#121315"
